// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineParkManagement.Migrations
{
    [DbContext(typeof(MachineParkManagementContext))]
    [Migration("20241228214040_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineParkManagement.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machine");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ac3dd63-8b48-4118-8279-1b66b88a8c6c"),
                            LastData = "Temp: 72C",
                            Name = "Machine 1",
                            Status = "Online"
                        },
                        new
                        {
                            Id = new Guid("42508173-0138-4e8c-b29f-006e477300a3"),
                            LastData = "Temp: 68C",
                            Name = "Machine 2",
                            Status = "Offline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
